ContentlistPageBlock:
    type: object
    inherits:
        - BasePageBlock
    config:
        fields:
            contentId:
                type: Item
                resolve: '@=query("EmbedAttributeValue", value.getAttribute("contentId").getValue())'
            limit:
                type: Int
                resolve: '@=value.getAttribute("limit").getValue()'
            contentType:
                type: '[ContentType]'
                resolve: '@=query("ContentTypeListStorageValue", value.getAttribute("contentType").getValue())'
