ImageItem:
    type: object
    inherits:
        - AbstractItem
    config:
        interfaces:
            - Item
            - Node
        fields:
            name:
                type: String
                resolve: '@=query("ItemFieldValue", value, "name", args)'
                args:
                    language: { type: RepositoryLanguage }
            caption:
                type: RichTextFieldValue
                resolve: '@=query("ItemFieldValue", value, "caption", args)'
                args:
                    language: { type: RepositoryLanguage }
            image:
                type: ImageFieldValue
                resolve: '@=query("ItemFieldValue", value, "image", args)'
                args:
                    language: { type: RepositoryLanguage }
            tags:
                type: '[String]'
                resolve: '@=query("ItemFieldValue", value, "tags", args) !== null ? query("ItemFieldValue", value, "tags", args).values : null'
                args:
                    language: { type: RepositoryLanguage }
