ItemGroupUsers:
    type: object
    inherits:
        - DomainContentTypeGroup
    config:
        fields:
            _types:
                type: ItemGroupUsersTypes
                resolve: {  }
            editors:
                type: EditorItemConnection
                resolve: '@=query("ItemsOfTypeAsConnection", "editor", args)'
                argsBuilder: 'Relay::Connection'
                args:
                    query: { type: ContentSearchQuery, description: 'A Content query used to filter results' }
                    sortBy: { type: '[SortByOptions]', description: 'A Sort Clause, or array of Clauses. Add _desc after a Clause to reverse it' }
            editor:
                type: EditorItem
                resolve: '@=query("ItemOfType", args, "editor")'
                args:
                    contentId: { type: Int, description: 'Content ID of the editor' }
                    remoteId: { type: String, description: 'Content remote ID of the editor' }
                    locationId: { type: Int, description: 'Location ID of the editor' }
                    locationRemoteId: { type: String, description: 'Location remote ID of the editor' }
                    urlAlias: { type: String, description: 'URL alias of the editor' }
            customers:
                type: CustomerItemConnection
                description: 'No description available'
                resolve: '@=query("ItemsOfTypeAsConnection", "customer", args)'
                argsBuilder: 'Relay::Connection'
                args:
                    query: { type: ContentSearchQuery, description: 'A Content query used to filter results' }
                    sortBy: { type: '[SortByOptions]', description: 'A Sort Clause, or array of Clauses. Add _desc after a Clause to reverse it' }
            customer:
                type: CustomerItem
                description: 'No description available'
                resolve: '@=query("ItemOfType", args, "customer")'
                args:
                    contentId: { type: Int, description: 'Content ID of the customer' }
                    remoteId: { type: String, description: 'Content remote ID of the customer' }
                    locationId: { type: Int, description: 'Location ID of the customer' }
                    locationRemoteId: { type: String, description: 'Location remote ID of the customer' }
                    urlAlias: { type: String, description: 'URL alias of the customer' }
            users:
                type: UserItemConnection
                description: 'No description available'
                resolve: '@=query("ItemsOfTypeAsConnection", "user", args)'
                argsBuilder: 'Relay::Connection'
                args:
                    query: { type: ContentSearchQuery, description: 'A Content query used to filter results' }
                    sortBy: { type: '[SortByOptions]', description: 'A Sort Clause, or array of Clauses. Add _desc after a Clause to reverse it' }
            user:
                type: UserItem
                description: 'No description available'
                resolve: '@=query("ItemOfType", args, "user")'
                args:
                    contentId: { type: Int, description: 'Content ID of the user' }
                    remoteId: { type: String, description: 'Content remote ID of the user' }
                    locationId: { type: Int, description: 'Location ID of the user' }
                    locationRemoteId: { type: String, description: 'Location remote ID of the user' }
                    urlAlias: { type: String, description: 'URL alias of the user' }
            userGroups:
                type: UserGroupItemConnection
                description: 'No description available'
                resolve: '@=query("ItemsOfTypeAsConnection", "user_group", args)'
                argsBuilder: 'Relay::Connection'
                args:
                    query: { type: ContentSearchQuery, description: 'A Content query used to filter results' }
                    sortBy: { type: '[SortByOptions]', description: 'A Sort Clause, or array of Clauses. Add _desc after a Clause to reverse it' }
            userGroup:
                type: UserGroupItem
                description: 'No description available'
                resolve: '@=query("ItemOfType", args, "user_group")'
                args:
                    contentId: { type: Int, description: 'Content ID of the user_group' }
                    remoteId: { type: String, description: 'Content remote ID of the user_group' }
                    locationId: { type: Int, description: 'Location ID of the user_group' }
                    locationRemoteId: { type: String, description: 'Location remote ID of the user_group' }
                    urlAlias: { type: String, description: 'URL alias of the user_group' }
