ItemGroupCustomerPortalTypes:
    type: object
    config:
        fields:
            customerPortal:
                type: CustomerPortalItemType
                resolve: '@=query("ContentType", {"identifier": "customer_portal"})'
            customerPortalPage:
                type: CustomerPortalPageItemType
                resolve: '@=query("ContentType", {"identifier": "customer_portal_page"})'
