TargetingPageBlock:
    type: object
    inherits:
        - BasePageBlock
    config:
        fields:
            defaultContentId:
                type: Item
                resolve: '@=query("EmbedAttributeValue", value.getAttribute("default_content_id").getValue())'
