/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/pages/{locationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a page builder page as a flat dto. */
        get: operations["get_app_api_v1_page_show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A page builder page, flattened to a domain-shaped tree of zones and blocks. No ibexa concepts leak into this shape. */
        PageDto: {
            /** @description Location id this page was loaded from. */
            locationId: number;
            /** @description Content id backing the location. */
            contentId: number;
            /** @description Layout identifier (e.g. default, two_columns). */
            layout: string;
            /** @description Page title (content name). */
            title: string;
            zones: components["schemas"]["ZoneDto"][];
        };
        /** @description A named layout zone holding an ordered list of blocks. */
        ZoneDto: {
            /** @description Stable zone id (uuid). */
            id: string;
            /** @description Zone name as defined by the layout (e.g. top, main, sidebar). */
            name: string;
            blocks: components["schemas"]["BlockDto"][];
        };
        /** @description A flat representation of a page builder block, decoupled from ibexa. */
        BlockDto: {
            /** @description Stable block id (uuid). */
            id: string;
            /** @description Block type identifier (e.g. richtext, embed, gallery). */
            type: string;
            /**
             * @description Block view name.
             * @example default
             */
            view: string;
            /** @description Optional editor-assigned name. */
            name?: string | null;
            /** @description Block-specific attributes. Shape depends on `type`. */
            attributes: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_app_api_v1_page_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locationId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageDto"];
                };
            };
            /** @description No page builder content at this location. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
